### ISSUE TITLE
Error with Toast component when Testing 

### ISSUE THREAD

**Issue by zeenatbaig** [jpmorganchase/salt-ds#3063]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

"@salt-ds/core": "^1.15.0",

### Description

Im running some jest tests with the toast component and im getting the following error 
TypeError: _a.scrollIntoView is not a function

  at node_modules/@salt-ds/core/dist-cjs/src/toast/Toast.tsx:40:23
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:20573:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20634:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23151:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at node_modules/react-dom/cjs/react-dom.development.js:11327:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11322:9)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11309:3)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22387:7)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at Object.eventWrapper (node_modules/@testing-library/react/dist/pure.js:65:28)
      at fireEvent (node_modules/@testing-library/dom/dist/events.js:16:35)
      at Function.fireEvent.<computed> [as change] (node_modules/@testing-library/dom/dist/events.js:125:36)
      at Function.fireEvent.<computed> [as change] (node_modules/@testing-library/react/dist/fire-event.js:18:52)

### Steps to reproduce

Im using toast within a combo box from the jpmuitk. When the toast is popping up. The tests throw that error

### Expected behavior

pass the test without throwing an error 

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
jsdom doesn't support this, try the setup suggested [here](https://github.com/jsdom/jsdom/issues/1695#issuecomment-449931788)
```
Element.prototype.scrollIntoView = jest.fn(); 
```

**Comment by origami-z** [comment]
This is no longer an issue given `scrollIntoView` is removed from Toast in #3038.
