### ISSUE TITLE
Theme Editor App gives error - React is not defined

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#379]
For some reason, automatic esbuild jsx runtime is not working

```
yarn
yarn modular start @jpmorganchase/theme-editor-app
```

```
Uncaught ReferenceError: React is not defined
    at ../../packages/icons/src/components/OverflowMenu.tsx (OverflowMenu.tsx:3:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../packages/lab/src/toolbar/overflow-panel/OverflowPanel.tsx (renderTrayTools.tsx:88:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../packages/lab/src/toolbar/Toolbar.tsx (useTokenizedInput.tsx:720:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../packages/lab/src/app-header/AppHeader.tsx (AccordionSummary.tsx:61:1)
```

Same error in prod build: 

```
yarn
yarn modular build @jpmorganchase/theme-editor-app
yarn modular serve @jpmorganchase/theme-editor-app
```

**Comment by origami-z** [comment]
The workaround is putting in `tsconfig.json` for each app config, as `extends` is not taken in  

```
  "compilerOptions": {
    "jsx": "react-jsx"
  },
```

Thanks @joshwooding finding the workaround. cc @libertymayc

**Comment by joshwooding** [comment]
Fixed
