### ISSUE TITLE
Dialog component causes 'slot):not([inert]' is not a valid selector in jets

### ISSUE THREAD

**Issue by TomGruner85** [jpmorganchase/salt-ds#4031]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.34.0

### Description

I use the Dialog component and when running unit tests using jest (v 29.5.0) and @testing-library/react (v 14.0.0), I get the following error message:

SyntaxError: 'slot):not([inert]' is not a valid selector

      at emit (node_modules/nwsapi/src/nwsapi.js:557:17)
      at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1400:9)
      at Array.Resolver (eval at compile (node_modules/nwsapi/src/nwsapi.js:760:17), <anonymous>:3:68)
      at match_assert (node_modules/nwsapi/src/nwsapi.js:1342:13)
      at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1360:16)
      at getCandidatesIteratively (node_modules/@floating-ui/react/dist/floating-ui.react.umd.js:1718:38)
      at tabbable (node_modules/@floating-ui/react/dist/floating-ui.react.umd.js:2098:20)
      at node_modules/@floating-ui/react/dist/floating-ui.react.umd.js:2852:34
      at safelyCallDestroy (node_modules/react-dom/cjs/react-dom.development.js:22932:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24103:23)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24062:11)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24170:9)

### Steps to reproduce

1. Write a component that renders the Dialog component
2. Write a test case to render this component
3. Observe the error 

### Expected behavior

Test cases for the Dialog component should pass.

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Which version of jsdom are you running? I can't reproduce this using 

```
npm list jsdom nwsapi
/temp/vite-salt
├─┬ jsdom@22.0.0
│ └── nwsapi@2.2.10
```

Tried with test code from [default example](https://www.saltdesignsystem.com/salt/components/dialog/examples)
```
  test("can render Dialog", async () => {
    render(
      <SaltProviderNext>
        <Default />
      </SaltProviderNext>
    );
    expect(
      screen.getByRole("button", { name: "Open default dialog" })
    ).toBeInTheDocument();
    userEvent.click(
      screen.getByRole("button", { name: "Open default dialog" })
    );
    expect(await screen.findByRole("dialog")).toBeInTheDocument();
    screen.debug();
  });
```

**Comment by TomGruner85** [comment]
I'm using jest-environment-jsdom, which uses jsdom under the hood:

├─┬ jest-environment-jsdom@29.5.0
│ ├── @jest/environment@29.5.0
│ ├── @jest/fake-timers@29.5.0
│ ├── @jest/types@29.5.0
│ ├── @types/jsdom@20.0.1
│ ├── @types/node@20.2.1 deduped
│ ├── UNMET OPTIONAL DEPENDENCY canvas@^2.5.0
│ ├── jest-mock@29.5.0
│ ├── jest-util@29.5.0
│ └── **jsdom@20.0.3**

**Comment by origami-z** [comment]
> I'm using jest-environment-jsdom, which uses jsdom under the hood:

which version of `nwsapi`?

**Comment by TomGruner85** [comment]
I'm not using nwsapi. I installed it and now tests are passing. Why is this not declared as a dependency in salt-ds?

**Comment by origami-z** [comment]
It is not salt dependency, but `jsdom`. Your previous dependency is out dated.

**Comment by origami-z** [comment]
With more testing, this error is a problem specifically with `nwsapi` with `2.2.3` and `2.2.4`. To confirm whether you're experiencing the same, run `npm list nwsapi` to see which version are you using.

If you have above problematic version installed, you'll need to upgrade them to at least `2.2.5` (check latest version on [npm](https://www.npmjs.com/package/nwsapi)). I didn't find a straightforward command to update this, given it's likely a transient dependency in your project. Something like below should work

- With npm, you can do `npm install nwsapi && npm uninstall nwsapi`
- With yarn@1, you can do `yarn add nwsapi && yarn remove nwsapi`
